"""
RiskMind Data Enrichment -- ChromaDB
Adds new guidelines, decisions, regulatory docs, cat commentary, and 2023 claims.
Run from backend/ directory: python enrich_chromadb.py
"""
import os
import chromadb

CHROMA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "chroma_db")

def run():
    client = chromadb.PersistentClient(path=os.path.abspath(CHROMA_DIR))

    guidelines_col = client.get_or_create_collection(name="guidelines")
    knowledge_col = client.get_or_create_collection(name="knowledge")

    print(f"Before: guidelines={guidelines_col.count()}, knowledge={knowledge_col.count()}")

    # ========================================================================
    # SECTION 1: 11 new guidelines (section 8.x.x)
    # ========================================================================
    guideline_ids = []
    guideline_docs = []
    guideline_metas = []

    guidelines = [
        {
            "id": "guideline_8.1.1",
            "doc": "Section 8.1.1 - Construction Safety Audit Requirement: Construction accounts with 3 or more workers compensation claims within a rolling 12-month period require a third-party safety audit before renewal consideration. The safety audit must be conducted by an approved vendor from the company's qualified inspector list and must include: workplace safety protocols review, equipment maintenance records, OSHA compliance verification, employee training documentation, and site hazard assessment. If the audit reveals critical safety deficiencies (score below 60 on the standardized assessment), the policy must be referred to senior underwriting for decline consideration. Audit costs are borne by the insured. This guideline applies to all construction industry policies regardless of premium size. Construction accounts with catastrophic claims (single claim exceeding $100,000) require immediate safety audit regardless of frequency. Reference: UW Guidelines v4.2, effective March 2024. Cross-reference: Section 3.1.1 (frequency threshold), Section 4.3.2 (catastrophic event).",
            "meta": {"section_code": "8.1.1", "title": "Construction Safety Audit", "category": "industry_specific"}
        },
        {
            "id": "guideline_8.1.2",
            "doc": "Section 8.1.2 - Transportation Fleet Safety Requirements: All transportation accounts must maintain a fleet safety score above 75 on the company's standardized fleet assessment scale. The assessment considers: driver MVR records, DOT compliance history, vehicle maintenance logs, telematics data (if available), hours-of-service violations, and accident frequency per million miles driven. Accounts scoring below 60 are ineligible for standard commercial auto programs and must be declined. Scores between 60-75 require enhanced monitoring including quarterly loss control reviews and mandatory driver safety training programs. Transportation accounts with 3 or more auto accident claims in a 12-month period are automatically flagged for fleet review regardless of overall score. Fleet score must be updated annually at renewal. New business requires fleet assessment within 30 days of binding. Reference: UW Guidelines v4.2, Section 8.1.2. Cross-reference: Section 3.1.1 (claim frequency).",
            "meta": {"section_code": "8.1.2", "title": "Transportation Fleet Requirements", "category": "industry_specific"}
        },
        {
            "id": "guideline_8.2.1",
            "doc": "Section 8.2.1 - Coastal Hurricane Deductible Requirements: All commercial properties located within 25 miles of the Gulf of Mexico or Atlantic Ocean coastline in Florida, Texas, Louisiana, North Carolina, and South Carolina require a minimum 2% named-storm or hurricane deductible applied to the building and contents replacement cost value. Properties located in FEMA-designated VE (Velocity) flood zones require an enhanced 5% wind/named-storm deductible due to elevated storm surge and wind exposure. No exceptions to these deductible minimums without written approval from the Chief Underwriting Officer. Properties in FEMA AE zones within 10 miles of coast require evaluation for wind-driven water damage exclusion. Cat model PML at 250-year return period must be documented for all coastal properties. If PML exceeds 40% of insured value, refer to catastrophe management team. Reference: UW Guidelines v4.2, effective January 2024. Supersedes prior coastal deductible memo dated July 2022.",
            "meta": {"section_code": "8.2.1", "title": "Coastal Hurricane Deductible", "category": "geographic"}
        },
        {
            "id": "guideline_8.2.2",
            "doc": "Section 8.2.2 - Flood Zone Underwriting Restrictions: Strict underwriting controls apply based on FEMA flood zone designation. Zone V and VE (coastal high-hazard areas): No new business without CUO written approval. Existing renewals require annual flood zone re-verification and elevation certificate. Zone AE (100-year floodplain): New business permitted with mandatory flood sublimit endorsement, current elevation certificate (less than 6 months old), and minimum $100,000 flood deductible. Zone AE policies must carry separate flood insurance. Zone X500 (500-year floodplain): Standard underwriting applies but policyholder must be notified of residual flood risk in writing. Zone X (minimal flood hazard): Standard underwriting. IMPORTANT: Properties with flood_zone_change_flag = 'UPGRADED' (recently remapped from X to AE) require immediate review of coverage terms and pricing. Premium adjustment of 15-25% recommended for zone upgrades. Reference: FEMA NFHL dataset, First Street Foundation risk model. Cross-reference: Section 4.2.1 (aggregate threshold).",
            "meta": {"section_code": "8.2.2", "title": "Flood Zone Restrictions", "category": "geographic"}
        },
        {
            "id": "guideline_8.2.3",
            "doc": "Section 8.2.3 - Wildfire Risk Assessment and Mitigation: Properties assigned a wildfire risk score above 70 (on the 0-100 NOAA/company composite scale) require a defensible space inspection before coverage can be bound or renewed. The inspection must verify: minimum 100-foot defensible space perimeter, non-combustible roofing materials, cleared gutters and vents, maintained access roads for emergency vehicles, and proximity to fire station (must be within 5 miles of career fire department or 8 miles of volunteer station). Wildfire risk score above 85 requires automatic decline for new business applications in California per state regulatory guidance (California FAIR Plan referral recommended). Existing California renewals with score above 85 require documented loss control visit within 60 days, 25% rate surcharge, and annual re-inspection. Properties within declared wildfire perimeters or evacuation zones within the past 3 years are ineligible. Reference: Cal DOI Bulletin 2024-3, NOAA wildfire risk database. Cross-reference: Section 6.1.1 (property coverage limits).",
            "meta": {"section_code": "8.2.3", "title": "Wildfire Risk Assessment", "category": "geographic"}
        },
        {
            "id": "guideline_8.3.1",
            "doc": "Section 8.3.1 - Zone Concentration Limit (TIV): Total insured value in any single CRESTA zone shall not exceed $7,000,000 without Chief Underwriting Officer approval. This threshold is calibrated for the current book size (21 policies, approximately $35M total TIV) and should be adjusted proportionally as the portfolio grows. New business applications that would cause any CRESTA zone to exceed the $7M TIV threshold must be referred to senior underwriting with a concentration impact assessment. Existing breaches (zones currently above threshold) require quarterly monitoring reports submitted to the CUO, a documented plan for planned exposure reduction (non-renewal of worst-performing policies in the zone), and suspension of new business in the breached zone until TIV falls below 95% of the threshold. Zone TIV is computed as the sum of insured_value for all active policies in the zone. Quarter-over-quarter TIV changes exceeding 15% trigger automatic review. Reference: Company concentration management policy, Reinsurance Treaty Section 4.2.",
            "meta": {"section_code": "8.3.1", "title": "Zone Concentration Limit", "category": "concentration"}
        },
        {
            "id": "guideline_8.3.2",
            "doc": "Section 8.3.2 - PML Accumulation Limit: Probable Maximum Loss at the 250-year return period shall not exceed $5,000,000 per CRESTA zone per the terms of the reinsurance treaty (effective January 2024). PML is computed using the RMS North Atlantic Hurricane Model v23 for wind-exposed zones and the RMS US Earthquake Model for seismic zones. Breaches of the $5M PML threshold must be reported to the reinsurance broker within 5 business days per treaty notification requirements. New business in zones where PML has breached or is within 10% of the threshold ($4,500,000) is automatically suspended pending reinsurance approval. The catastrophe management team must review zone PML accumulation monthly and report to the CUO. PML calculations must include both the primary peril (wind, earthquake, flood) and secondary perils (fire following earthquake, demand surge, loss amplification). Reference: Reinsurance Treaty 2024, Section 4.2. Cat Model: RMS v23. Cross-reference: Section 8.3.1 (TIV concentration).",
            "meta": {"section_code": "8.3.2", "title": "PML Accumulation Limit", "category": "concentration"}
        },
        {
            "id": "guideline_8.4.1",
            "doc": "Section 8.4.1 - Credit Underwriting Standards: Commercial accounts are evaluated using Dun & Bradstreet commercial credit scores (0-100 scale). Score 70+: Standard underwriting, no additional requirements. Score 50-69: Acceptable with documentation of credit trend (improving vs declining). Declining credit over 2 consecutive quarters requires underwriter note in file. Score 40-49: Requires senior underwriter approval with documented rationale for acceptance. Consider requiring higher deductibles or payment plan restrictions. Score 30-39: Automatic referral to senior underwriting. Binding authority suspended for line underwriters. Score below 30: Automatic decline. No exceptions without CUO written approval and documented extraordinary circumstances. Financial stability indicator (Stable/Improving/Declining/New) must be documented at new business and renewal. Accounts transitioning from Stable to Declining require proactive review within 30 days. New businesses (less than 2 years operating) without established credit require personal guarantee from principals. Reference: D&B Commercial Credit database, updated monthly. Cross-reference: Section 2.1.2 (financial standing).",
            "meta": {"section_code": "8.4.1", "title": "Credit Underwriting Standards", "category": "financial"}
        },
        {
            "id": "guideline_8.4.2",
            "doc": "Section 8.4.2 - Under-Insurance Detection and ITV Compliance: Insurance-to-Value (ITV) analysis is mandatory at new business and renewal. If the property replacement cost (from CoreLogic Property data or recent appraisal) exceeds the declared insured value by more than 25% (ITV ratio below 0.80), the policy is flagged for ITV clause review and premium adjustment. Underwriter actions required: (1) Document ITV discrepancy in policy file, (2) Notify broker/agent of replacement cost gap with specific dollar amounts, (3) Recommend insured value increase to at least 90% of replacement cost, (4) If insured declines adjustment, apply co-insurance endorsement (80% co-insurance clause minimum). Policies with replacement cost ratio above 1.40 (insured value less than 71% of replacement cost) require mandatory co-insurance endorsement regardless of insured's preference. Over-insurance (insured value exceeding replacement cost by more than 15%) should also be flagged as potential moral hazard indicator. Reference: CoreLogic Property Characteristics database, updated semi-annually. ISO ITV guidelines.",
            "meta": {"section_code": "8.4.2", "title": "Under-Insurance Detection", "category": "financial"}
        },
        {
            "id": "guideline_8.5.1",
            "doc": "Section 8.5.1 - Third-Party Data Requirements for Underwriting: All new business submissions and renewals with Total Insured Value exceeding $1,000,000 require current third-party data verification before binding or renewal confirmation. Required data elements: (1) FEMA flood zone verification (less than 6 months old from FEMA NFHL or First Street Foundation), (2) Catastrophe model output (RMS v23 or equivalent - AAL, PML-250yr, primary peril), (3) Property characteristics verification (CoreLogic or equivalent - construction type, year built, roof type, protection class), (4) Commercial credit score (D&B, updated within 90 days). Properties in catastrophe-exposed zones (wind, earthquake, wildfire risk score above 50) require full RMS model run with secondary peril analysis. All data must be documented in the electronic policy file with data source, date retrieved, and data version. Stale data (more than 12 months old) is not acceptable for binding decisions. Reference: Company data governance policy, effective January 2024. Cross-reference: Section 8.5.2 (NAIC compliance).",
            "meta": {"section_code": "8.5.1", "title": "Third-Party Data Requirements", "category": "compliance"}
        },
        {
            "id": "guideline_8.5.2",
            "doc": "Section 8.5.2 - NAIC AI Compliance Requirements: Per the NAIC Model Bulletin on Use of Artificial Intelligence Systems by Insurers (issued December 4, 2023, adopted by 23 states plus District of Columbia as of late 2025), all AI-assisted underwriting decisions produced by the RiskMind system must include the following documentation: (1) Data Sources Used - list all third-party and internal data sources that informed the decision (FEMA, RMS, CoreLogic, D&B, internal claims/guidelines), (2) Guidelines Cited - specific section codes and threshold values that were evaluated, (3) Confidence Score - the system's confidence level (0-100) in the recommendation, with scores below 60 flagged for mandatory human review, (4) Recommendation Rationale - clear natural language explanation of why the AI reached its conclusion, (5) Human Reviewer Identity - email and role of the underwriter who reviewed and approved/modified the AI recommendation. The Glass Box evidence panel in RiskMind is designed to satisfy requirements (1) through (4). Requirement (5) is satisfied by the login-authenticated decision workflow. Non-compliance with these documentation requirements may result in regulatory examination findings under state-adopted versions of the NAIC bulletin. Reference: NAIC Model Bulletin Dec 2023, Quarles & Brady state adoption tracker, NYDFS Circular Letter 2024-XX.",
            "meta": {"section_code": "8.5.2", "title": "NAIC AI Compliance", "category": "compliance"}
        },
    ]

    for g in guidelines:
        guideline_ids.append(g["id"])
        guideline_docs.append(g["doc"])
        guideline_metas.append(g["meta"])

    guidelines_col.upsert(ids=guideline_ids, documents=guideline_docs, metadatas=guideline_metas)
    print(f"[OK] Upserted {len(guideline_ids)} new guidelines")

    # ========================================================================
    # SECTION 2: 15 decision documents
    # ========================================================================
    dec_ids = []
    dec_docs = []
    dec_metas = []

    decisions = [
        # 5 ACCEPT
        {"id": "DEC-2024-001", "pn": "COMM-2024-007", "name": "GreenLeaf Properties", "ind": "Real Estate", "dec": "accept", "risk": "LOW", "by": "sarah@apexuw.com", "date": "2024-08-15",
         "doc": "Underwriting Decision - ACCEPT - Policy COMM-2024-007 (GreenLeaf Properties, Real Estate). Decision Date: 2024-08-15. Decided by: sarah@apexuw.com. Risk Level: LOW. Reason: Clean loss history with zero claims filed during the current policy period. All eligibility guidelines met including Section 1.1.1 (standard eligibility) and Section 2.1.1 (business age - operational since 2005, exceeding 2-year minimum). D&B commercial credit score of 88, well above Section 2.1.2 threshold. Financial stability indicator: Improving, with revenue growth of 12% year-over-year. Property located in Phoenix AZ, FEMA flood zone X with minimal flood risk (score 12). Masonry construction built 2005, protection class 3. Cat model shows low peril exposure (Hail, AAL $5,500). Loss ratio 0%. Key Factors: Loss ratio 0%, 0 claims, credit score 88, flood zone X, CRESTA zone US-AZ-001. Guidelines Applied: Section 1.1.1 (met), Section 2.1.2 (met - score 88 vs threshold 650 equiv), Section 5.1.1 (favorable LR under 50%). Recommendation: Standard renewal at current terms with 3% loyalty credit."},
        {"id": "DEC-2024-002", "pn": "COMM-2024-006", "name": "TechNova Solutions", "ind": "Technology", "dec": "accept", "risk": "LOW", "by": "james@apexuw.com", "date": "2024-11-20",
         "doc": "Underwriting Decision - ACCEPT - Policy COMM-2024-006 (TechNova Solutions, Technology). Decision Date: 2024-11-20. Decided by: james@apexuw.com. Risk Level: LOW. Reason: Single minor cyber breach claim of $5,000 (closed, resolved within 30 days). Loss ratio 12.5%, well within favorable threshold per Section 5.1.1. Strong D&B credit score of 82 with stable financials. Fire-resistive construction in San Francisco, built 2015. Earthquake exposure present (primary peril) but PML $750K within zone tolerance. Technology sector shows strong growth trajectory. Current cyber security posture assessed as adequate. Key Factors: Loss ratio 12.5%, 1 claim totaling $5,000, credit score 82, flood zone X, CRESTA zone US-CA-002. Guidelines Applied: Section 5.1.1 (favorable LR), Section 1.1.1 (standard eligibility met). Recommendation: Standard renewal, consider cyber sublimit review at next term."},
        {"id": "DEC-2025-003", "pn": "COMM-2024-017", "name": "BlueSky Development", "ind": "Real Estate", "dec": "accept", "risk": "LOW", "by": "james@apexuw.com", "date": "2025-01-10",
         "doc": "Underwriting Decision - ACCEPT - Policy COMM-2024-017 (BlueSky Development, Real Estate). Decision Date: 2025-01-10. Decided by: james@apexuw.com. Risk Level: LOW. Reason: Zero claims filed. Excellent D&B credit score of 90, highest in portfolio. Financial stability: Improving with significant Austin TX real estate portfolio growth. Located in FEMA AE flood zone (recently upgraded from X per FEMA NFHL revision) but fire-resistive construction (2019), 8 stories, with adequate flood sublimit in place per Section 8.2.2. Hail exposure notable (14 events in 5 years) but metal-free roofing design mitigates. Loss ratio 0%. Key Factors: Loss ratio 0%, 0 claims, credit score 90, flood zone AE (upgraded), CRESTA zone US-TX-003. Guidelines Applied: Section 5.1.1 (favorable), Section 8.2.2 (flood sublimit confirmed), Section 2.1.2 (excellent credit). Recommendation: Standard renewal with flood endorsement per AE zone requirement."},
        {"id": "DEC-2024-004", "pn": "COMM-2024-001", "name": "ABC Manufacturing Inc", "ind": "Manufacturing", "dec": "accept", "risk": "LOW", "by": "sarah@apexuw.com", "date": "2024-09-05",
         "doc": "Underwriting Decision - ACCEPT - Policy COMM-2024-001 (ABC Manufacturing Inc, Manufacturing). Decision Date: 2024-09-05. Decided by: sarah@apexuw.com. Risk Level: LOW. Reason: Two property damage claims in current period totaling $23,500. Both claims are routine maintenance-type losses (equipment damage and pipe burst) typical for aging manufacturing facilities. Loss ratio 47%, within favorable range per Section 5.1.1. D&B credit score 71, above threshold. Stable financials. Detroit MI location in FEMA zone X, minimal flood risk. Masonry construction built 1978, replacement cost $1.85M vs insured value $1.6M (13% gap, within ITV tolerance per Section 8.4.2). Key Factors: Loss ratio 47%, 2 claims totaling $23,500, credit score 71, flood zone X, CRESTA US-MI-001. Guidelines Applied: Section 5.1.1 (favorable LR), Section 1.1.1 (met). Recommendation: Renewal with 5% rate increase to reflect claim frequency. Recommend property maintenance inspection."},
        {"id": "DEC-2025-005", "pn": "COMM-2024-013", "name": "SunValley Farms", "ind": "Agriculture", "dec": "accept", "risk": "LOW", "by": "sarah@apexuw.com", "date": "2025-02-01",
         "doc": "Underwriting Decision - ACCEPT - Policy COMM-2024-013 (SunValley Farms, Agriculture). Decision Date: 2025-02-01. Decided by: sarah@apexuw.com. Risk Level: LOW. Reason: Single storm damage claim of $22,000 (closed). Agriculture inherently exposed to weather events. Loss ratio 57.9% is moderate, within Section 5.1.2 range requiring pricing review. D&B credit score 75, stable financials. Bakersfield CA location with earthquake exposure (PML $280K) but manageable. Wildfire risk score 55 is elevated but below Section 8.2.3 threshold of 70. Protection class 6 reflects rural location. Key Factors: Loss ratio 57.9%, 1 claim totaling $22,000, credit score 75, flood zone X, CRESTA US-CA-003, wildfire score 55. Guidelines Applied: Section 5.1.2 (moderate LR - pricing review), Section 8.2.3 (wildfire below threshold). Recommendation: Renewal with 8% rate adjustment per Section 5.1.2 and weather deductible endorsement."},

        # 4 REFER
        {"id": "DEC-2025-006", "pn": "COMM-2024-005", "name": "FastTrack Logistics", "ind": "Transportation", "dec": "refer", "risk": "MEDIUM", "by": "sarah@apexuw.com", "date": "2025-01-15",
         "doc": "Underwriting Decision - REFER - Policy COMM-2024-005 (FastTrack Logistics, Transportation). Decision Date: 2025-01-15. Decided by: sarah@apexuw.com. Risk Level: MEDIUM. Reason: Four claims totaling $63,500 in current period, approaching Section 3.1.1 frequency threshold of 5 claims. Loss ratio 141.1%, significantly breaching Section 5.1.3 adverse threshold of 65%. Transportation fleet showing deteriorating year-over-year trend with 2 additional claims in 2024 versus 1 in 2023. D&B credit score 55 and declining trajectory. Dallas TX location with FEMA zone X but recently upgraded flood mapping (flag: UPGRADED). Per Section 8.1.2, fleet safety assessment required - current accident pattern suggests score likely below 75 threshold. Key Factors: Loss ratio 141.1%, 4 claims totaling $63,500, credit score 55 (declining), flood zone X (upgraded), CRESTA US-TX-003. Guidelines Applied: Section 3.1.1 (approaching breach), Section 5.1.3 (adverse LR), Section 8.1.2 (fleet review required). Recommendation: Refer to senior underwriter. Minimum 20% rate increase required if renewing. Fleet safety audit mandatory."},
        {"id": "DEC-2025-007", "pn": "COMM-2024-014", "name": "OceanView Hotels", "ind": "Hospitality", "dec": "refer", "risk": "MEDIUM", "by": "james@apexuw.com", "date": "2025-03-01",
         "doc": "Underwriting Decision - REFER - Policy COMM-2024-014 (OceanView Hotels, Hospitality). Decision Date: 2025-03-01. Decided by: james@apexuw.com. Risk Level: MEDIUM. Reason: Four claims totaling $48,500 across general liability and property damage categories. Loss ratio 93.3%, breaching Section 5.1.3 adverse threshold. Orlando FL location in FEMA AE flood zone (recently upgraded from X - flag: UPGRADED) with wind PML of $890K. Hospitality sector carries elevated GL exposure from guest activities. D&B credit score 58, borderline. 2023 claim history includes $85K business interruption from hurricane - total exposure significant. Per Section 8.2.1, coastal hurricane deductible of 2% required. Per Section 8.2.2, AE zone requires flood sublimit endorsement. Key Factors: Loss ratio 93.3%, 4 claims totaling $48,500 (plus $85K in 2023), credit score 58, flood zone AE (upgraded), CRESTA US-FL-001. Guidelines Applied: Section 5.1.3 (adverse LR), Section 8.2.1 (hurricane deductible), Section 8.2.2 (flood zone AE restrictions). Recommendation: Senior review required per Section 7.1.1. If renewing: 20% rate increase, 2% hurricane deductible, flood sublimit."},
        {"id": "DEC-2025-008", "pn": "COMM-2024-019", "name": "SteelEdge Manufacturing", "ind": "Manufacturing", "dec": "refer", "risk": "MEDIUM", "by": "sarah@apexuw.com", "date": "2025-04-15",
         "doc": "Underwriting Decision - REFER - Policy COMM-2024-019 (SteelEdge Manufacturing, Manufacturing). Decision Date: 2025-04-15. Decided by: sarah@apexuw.com. Risk Level: MEDIUM. Reason: Three claims in 2024 totaling $92,000 including open $45K workers compensation claim (forklift accident). Additional environmental claim of $32K in 2023. Loss ratio 131.4% based on 2024 data alone. Manufacturing facility built 1970, masonry construction with aging infrastructure concerns. Two of three 2024 claims are workers compensation, suggesting systemic workplace safety issues. Per Section 8.1.1 (adapted for manufacturing), safety audit recommended given WC frequency. D&B credit score 60, stable but not strong. Cleveland OH, CRESTA US-OH-001, SCS primary peril. Key Factors: Loss ratio 131.4%, 3 claims totaling $92,000, credit score 60, flood zone X500, CRESTA US-OH-001. Guidelines Applied: Section 5.1.3 (adverse LR), Section 3.1.1 (approaching frequency threshold), Section 8.1.1 (safety audit for WC frequency). Recommendation: Refer to senior underwriter. Safety audit required before renewal decision. If renewing: minimum 25% rate increase."},
        {"id": "DEC-2025-009", "pn": "P-1023", "name": "Northwind Logistics", "ind": "Transportation", "dec": "refer", "risk": "HIGH", "by": "james@apexuw.com", "date": "2025-05-01",
         "doc": "Underwriting Decision - REFER - Policy P-1023 (Northwind Logistics, Transportation). Decision Date: 2025-05-01. Decided by: james@apexuw.com. Risk Level: HIGH. Reason: Four claims in 2024 totaling $63,000 with open $24K auto accident claim involving injuries. Additional 2 claims in 2023 ($16,500). Deteriorating year-over-year trend: claim count went from 2 in 2023 to 4 in 2024 (100% increase, triggering Section 3.1.2 frequency trend analysis). Loss ratio 121.2%. Memphis TN location with high crime index of 68 and property crime rate 2.1x national average. D&B credit score 52 with financial stability: Declining. Per Section 8.1.2, fleet safety score likely below 75 given 3 auto accidents. Key Factors: Loss ratio 121.2%, 4 claims totaling $63,000 (2024), credit score 52 (declining), crime index 68, CRESTA US-TN-002. Guidelines Applied: Section 3.1.2 (50%+ frequency increase YoY), Section 5.1.3 (adverse LR), Section 8.1.2 (fleet review). Recommendation: Refer to senior UW with non-renewal recommendation unless fleet safety program implemented within 60 days."},

        # 4 DECLINE
        {"id": "DEC-2025-010", "pn": "COMM-2024-002", "name": "XYZ Restaurant Group", "ind": "Restaurant", "dec": "decline", "risk": "HIGH", "by": "sarah@apexuw.com", "date": "2025-06-01",
         "doc": "Underwriting Decision - DECLINE - Policy COMM-2024-002 (XYZ Restaurant Group, Restaurant). Decision Date: 2025-06-01. Decided by: sarah@apexuw.com. Risk Level: HIGH. Reason: Six claims in 2024 totaling $26,000 - breaches Section 3.1.1 frequency threshold of 5 claims triggering mandatory enhanced review. Additional $55K business interruption claim in 2023 from health department closure. Combined 2-year loss totaling $81,000. Loss ratio 74.3% on 2024 alone, 231.4% including 2023. Miami Beach FL location in FEMA AE flood zone with wind PML $980K - significant catastrophe exposure. D&B credit score 42, below Section 8.4.1 threshold of 40 for automatic senior review. Financial stability: Declining, with revenue down 15% and vendor payment delays reported. Multiple general liability claims (4 of 6) indicate systemic operational safety failures - inadequate maintenance, staff training, and food safety protocols. Key Factors: Loss ratio 74.3% (2024)/231.4% (combined), 6 claims, credit score 42 (declining), flood zone AE, CRESTA US-FL-001, wind PML $980K. Guidelines Applied: Section 3.1.1 (frequency BREACH), Section 5.1.3 (adverse LR), Section 8.4.1 (credit below 40 threshold), Section 8.2.1 (coastal hurricane deductible). Recommendation: Decline renewal. Issue non-renewal notice per state requirements. Recommend insured implement risk improvement plan for reconsideration in 12 months."},
        {"id": "DEC-2025-011", "pn": "COMM-2024-011", "name": "BuildRight Contractors", "ind": "Construction", "dec": "decline", "risk": "HIGH", "by": "sarah@apexuw.com", "date": "2025-07-01",
         "doc": "Underwriting Decision - DECLINE - Policy COMM-2024-011 (BuildRight Contractors, Construction). Decision Date: 2025-07-01. Decided by: sarah@apexuw.com. Risk Level: HIGH. Reason: Two claims in 2024 including $250K building collapse - catastrophic event breaching Section 4.3.2 threshold of $100K and Section 4.2.1 aggregate threshold of $200K. Total 2024 claims $285,000. Historical 2023 data shows 3 additional claims totaling $180K including a $120K trench collapse. Combined 2-year claims: $465,000. Loss ratio 356.3% on 2024 alone, 581.3% combined. D&B credit score 32 - severely below Section 8.4.1 threshold, approaching automatic decline at 30. Financial stability: Declining. Los Angeles CA location with earthquake PML $1.2M (highest in portfolio). Frame construction from 1985 with wildfire score 62 (approaching Section 8.2.3 threshold of 70). Per Section 8.1.1, construction safety audit would be required but given catastrophic loss history, audit is unlikely to yield acceptable results. Key Factors: Loss ratio 356.3%/581.3%, $250K single event, credit score 32, earthquake PML $1.2M, wildfire score 62, CRESTA US-CA-001. Guidelines Applied: Section 4.3.2 (catastrophic BREACH), Section 4.2.1 (aggregate BREACH), Section 8.4.1 (credit near auto-decline), Section 8.1.1 (safety audit required but futile). Recommendation: Decline. Non-renewal effective immediately at policy expiration. Do not entertain reconsideration for minimum 24 months."},
        {"id": "DEC-2025-012", "pn": "COMM-2024-008", "name": "CityBite Foods LLC", "ind": "Restaurant", "dec": "decline", "risk": "HIGH", "by": "james@apexuw.com", "date": "2025-08-15",
         "doc": "Underwriting Decision - DECLINE - Policy COMM-2024-008 (CityBite Foods LLC, Restaurant). Decision Date: 2025-08-15. Decided by: james@apexuw.com. Risk Level: HIGH. Reason: Five claims in 2024 totaling $19,500 - breaches Section 3.1.1 frequency threshold. Despite low individual claim amounts, the persistent frequency pattern (5 claims in 12 months) indicates chronic operational failures in customer safety, food handling, and premises maintenance. New York NY location with crime index 42. D&B credit score 35, below Section 8.4.1 threshold of 40 requiring senior review, approaching automatic decline at 30. Financial stability: Declining, with reported cash flow issues. Loss ratio 65%, at the boundary of adverse territory per Section 5.1.3. Combined with poor credit, high frequency, and declining financials, risk profile is unacceptable for standard program. Key Factors: Loss ratio 65%, 5 claims, credit score 35 (declining), flood zone X, CRESTA US-NY-001. Guidelines Applied: Section 3.1.1 (frequency BREACH), Section 8.4.1 (credit below 40), Section 5.1.2/5.1.3 (LR at boundary). Recommendation: Decline renewal. Non-renewal notice per NY state requirements (90 days). Risk improvement plan required before reconsideration."},
        {"id": "DEC-2025-013", "pn": "COMM-2024-003", "name": "SafeBuild Construction", "ind": "Construction", "dec": "decline", "risk": "HIGH", "by": "sarah@apexuw.com", "date": "2025-09-01",
         "doc": "Underwriting Decision - DECLINE - Policy COMM-2024-003 (SafeBuild Construction, Construction). Decision Date: 2025-09-01. Decided by: sarah@apexuw.com. Risk Level: HIGH. Reason: Three claims in 2024 including $175K crane collapse with multiple injuries - breaches Section 4.1.1 single claim severity threshold of $100K and Section 4.3.2 catastrophic event threshold. Total 2024 claims $215,500. Historical 2023 data shows 4 additional claims totaling $153K including $65K equipment rollover and $45K scaffolding collapse. Combined 2-year claims: $368,500 against $75K premium. Loss ratio 287.3% (2024) / 491.3% (combined). D&B credit score 38, below Section 8.4.1 threshold. Financial stability: Declining. Per Section 8.1.1 construction safety audit is mandatory given 3+ WC claims, but catastrophic loss history and declining financials make rehabilitation unlikely. Denver CO location with hail exposure (12 events/5yr). Key Factors: Loss ratio 287.3%/491.3%, $175K catastrophic event, credit score 38, 7 claims over 2 years (WC dominant), CRESTA US-CO-001. Guidelines Applied: Section 4.1.1 (severity BREACH), Section 4.3.2 (catastrophic BREACH), Section 8.1.1 (safety audit mandatory), Section 8.4.1 (credit below 40). Recommendation: Decline. Immediate non-renewal. Report to OSHA if workplace safety patterns indicate compliance failure."},

        # 2 NON-RENEWAL
        {"id": "DEC-2025-014", "pn": "COMM-2024-016", "name": "Eagle Transport Co", "ind": "Transportation", "dec": "decline", "risk": "HIGH", "by": "sarah@apexuw.com", "date": "2025-10-01",
         "doc": "Underwriting Decision - NON-RENEWAL - Policy COMM-2024-016 (Eagle Transport Co, Transportation). Decision Date: 2025-10-01. Decided by: sarah@apexuw.com. Risk Level: HIGH. Reason: Five claims in 2024 totaling $76,000 - breaches Section 3.1.1 frequency threshold. Four of five claims are auto accidents indicating systemic fleet safety failure. Deteriorating year-over-year trend: claim count increased from 2 in 2023 ($14,500) to 5 in 2024 ($76,000) - 150% frequency increase and 424% severity increase, massively triggering Section 3.1.2 trend analysis (threshold: 50% increase). Loss ratio 158.3%. Chicago IL location with crime index 60 and property crime rate 1.7x. D&B credit score 45, declining. Per Section 8.1.2, fleet safety score is estimated below 60 (automatic decline threshold) given 4 auto accidents in 12 months. Key Factors: Loss ratio 158.3%, 5 claims (4 auto), credit score 45, frequency trend +150% YoY, CRESTA US-IL-001. Guidelines Applied: Section 3.1.1 (frequency BREACH), Section 3.1.2 (trend BREACH - 150% vs 50% threshold), Section 8.1.2 (fleet below 60 = decline). Recommendation: Non-renewal effective at policy expiration. Issue 60-day notice per IL requirements. Fleet safety remediation program required before any reconsideration."},
        {"id": "DEC-2025-015", "pn": "COMM-2024-010", "name": "QuickMart Retail Chain", "ind": "Retail", "dec": "refer", "risk": "MEDIUM", "by": "james@apexuw.com", "date": "2025-11-15",
         "doc": "Underwriting Decision - NON-RENEWAL RECOMMENDATION (REFER) - Policy COMM-2024-010 (QuickMart Retail Chain, Retail). Decision Date: 2025-11-15. Decided by: james@apexuw.com. Risk Level: MEDIUM. Reason: Three claims in 2024 totaling $18,500 in retail environment. Loss ratio 66.1%, in moderate-adverse range per Section 5.1.2 requiring pricing review. General liability frequency concerning - 2 of 3 claims are slip-and-fall or customer injury type, suggesting inadequate premises maintenance and housekeeping protocols. D&B credit score 62 but trending downward over past 2 quarters. Atlanta GA location with acceptable risk profile (FEMA X, SCS peril). Crime index 55 with property crime rate 1.5x reflects urban retail challenges. Key Factors: Loss ratio 66.1%, 3 claims, credit score 62 (declining trend), flood zone X, CRESTA US-GA-001. Guidelines Applied: Section 5.1.2 (moderate LR - pricing review), Section 5.1.3 (approaching adverse threshold). Recommendation: Non-renewal recommended unless insured provides documented evidence of premises safety improvements (anti-slip flooring, maintenance schedule, incident reporting system) and accepts 15% rate increase per Section 5.1.3."},
    ]

    for d in decisions:
        dec_ids.append(d["id"])
        dec_docs.append(d["doc"])
        dec_metas.append({
            "type": "decision",
            "decision_id": d["id"],
            "policy_number": d["pn"],
            "policyholder": d["name"],
            "industry": d["ind"],
            "decision": d["dec"],
            "risk_level": d["risk"],
            "decided_by": d["by"],
            "decision_date": d["date"],
        })

    knowledge_col.upsert(ids=dec_ids, documents=dec_docs, metadatas=dec_metas)
    print(f"[OK] Upserted {len(dec_ids)} decision documents")

    # ========================================================================
    # SECTION 3: 5 regulatory documents
    # ========================================================================
    reg_ids = []
    reg_docs = []
    reg_metas = []

    regs = [
        {
            "id": "REG-001",
            "doc": "NAIC Model Bulletin Summary - Use of Artificial Intelligence Systems by Insurers. Issued December 4, 2023 by the National Association of Insurance Commissioners. Adopted by 23 states plus the District of Columbia as of late 2025. Key Requirements: (1) Transparency and Explainability - insurers must be able to explain AI-driven underwriting, pricing, and claims decisions to consumers and regulators in clear, understandable terms. The explanation must include data inputs, decision logic, and outcome rationale. (2) Human Oversight - humans must remain accountable for AI-assisted decisions. AI recommendations are advisory; final authority rests with licensed underwriters. (3) Fairness and Non-Discrimination - AI systems must not produce unfairly discriminatory outcomes based on protected classes including race, gender, religion, national origin, or genetic information. Regular bias testing required. (4) Consumer Notification - insurers must notify consumers when AI materially affects underwriting, pricing, or claims decisions. Notification must be timely and explain how to request human review. (5) Third-Party Oversight - insurers are responsible for the explainability and fairness of AI systems provided by third-party vendors. Vendor contracts must include audit rights. (6) Data Governance - ensure quality, integrity, and appropriate use of data feeding AI systems. Prohibited data sources include facial recognition data and certain social media data. Compliance approach for RiskMind: The Glass Box evidence panel satisfies explainability requirements. The data sources registry (DS-001 through DS-013) satisfies data governance documentation. The login-authenticated decision workflow satisfies human oversight. Reference: NAIC.org, Quarles & Brady state adoption tracker, NYDFS Circular Letter 2024-XX.",
            "meta": {"type": "regulatory", "reg_id": "REG-001", "title": "NAIC AI Model Bulletin", "jurisdiction": "federal", "effective_date": "2023-12-04", "category": "ai_governance"}
        },
        {
            "id": "REG-002",
            "doc": "Texas Department of Insurance AI Guidance - Bulletin 2024-B-005: Use of AI in Property and Casualty Insurance. Effective June 1, 2024. Texas adopted the NAIC Model Bulletin with state-specific modifications. Key Texas Requirements: (1) All AI-assisted underwriting decisions for Texas risks must include documented data sources and guideline citations per NAIC Model Bulletin requirements. (2) Texas-specific: Insurers using AI for homeowners or commercial property underwriting in coastal counties (Harris, Galveston, Brazoria, Jefferson, Orange, Chambers, Matagorda, Calhoun, Aransas, Nueces, Kleberg, Kenedy, Willacy, Cameron) must additionally document hurricane/windstorm model outputs and explain how catastrophe model results influenced the decision. (3) Rate filings that incorporate AI-derived pricing factors must include model validation documentation. (4) Policyholders must be notified of the insurer's use of AI at application and renewal. (5) Texas prohibits use of credit-based insurance scores as sole determinant but permits as one factor in commercial lines. (6) Complaints regarding AI-driven decisions trigger enhanced regulatory review. RiskMind compliance: Cat model outputs (RMS v23) are stored per-policy. CRESTA zone accumulation is tracked. All decisions include guideline citations via Glass Box. Reference: TDI Bulletin 2024-B-005, Texas Insurance Code Chapter 544.",
            "meta": {"type": "regulatory", "reg_id": "REG-002", "title": "Texas DOI AI Guidance", "jurisdiction": "state-TX", "effective_date": "2024-06-01", "category": "ai_governance"}
        },
        {
            "id": "REG-003",
            "doc": "Florida Office of Insurance Regulation - Wind Exposure and Coastal Property Rules: OIR Informational Memorandum 2024-IM-02. Florida requires specific underwriting controls for wind-exposed commercial properties. Key Requirements: (1) All commercial property policies covering structures within the Florida Wind Exposure Territory (generally within 1 mile of coast for Palm Beach through Dade counties, varying for other coastal counties) must have separate named-storm deductibles of minimum 2% of insured value. (2) Properties in FEMA VE zones require 5% named-storm deductible and must carry separate flood insurance. (3) Insurers must file catastrophe model results (hurricane AAL and PML at 100-year and 250-year return periods) with rate filings. Approved models: AIR, RMS, CoreLogic. (4) Maximum policy limits for wind coverage: $10M per occurrence for any single commercial risk without prior OIR approval. (5) Citizens Property Insurance Corporation eligibility: Commercial risks that cannot obtain private market coverage at rates not exceeding Citizens' rates are eligible for Citizens commercial residential program. (6) Post-hurricane moratorium: Following a Category 3+ hurricane making FL landfall, 90-day moratorium on non-renewals and cancellations in affected counties. RiskMind compliance: Wind PML tracked per policy via cat model fields. Coastal deductible requirements embedded in Section 8.2.1 guidelines. Reference: OIR-IM-2024-02, Florida Statute 627.0628, Citizens Property Insurance Act.",
            "meta": {"type": "regulatory", "reg_id": "REG-003", "title": "Florida OIR Wind Exposure Rules", "jurisdiction": "state-FL", "effective_date": "2024-03-01", "category": "wind"}
        },
        {
            "id": "REG-004",
            "doc": "California Department of Insurance - Wildfire Risk and Insurance Guidance: CDI Bulletin 2024-3, effective April 2024. Addresses insurer obligations for wildfire-exposed properties in California. Key Requirements: (1) Insurers may not use wildfire risk alone to non-renew policies. Must consider policyholder's fire hardening efforts, defensible space maintenance, and community wildfire protection plans. (2) FAIR Plan referral required before any wildfire-related non-renewal. Insurers must provide 75-day non-renewal notice with specific wildfire risk factors cited. (3) Rate filings incorporating wildfire risk must use approved wildfire models and publicly available datasets. Proprietary models require CDI actuarial review. (4) Insurers offering commercial policies in State Responsibility Areas (SRA) must participate in the California FAIR Plan as a condition of doing business. (5) Moratorium zones: Following a wildfire event, CDI may impose 1-year moratorium on non-renewals and cancellations for all residential and commercial policies in affected ZIP codes. (6) Disclosure requirements: Insurers must disclose to applicants and policyholders the wildfire risk score used and the data sources supporting the score. (7) New for 2025: Insurers must accept applications from properties that have achieved Firewise USA certification regardless of underlying wildfire risk score. RiskMind compliance: Wildfire risk scores tracked per policy. Section 8.2.3 guidelines align with CDI requirements. Decline threshold set at 85 for new CA business. Reference: CDI Bulletin 2024-3, CA Insurance Code Section 675.1, CDI FAIR Plan guidance.",
            "meta": {"type": "regulatory", "reg_id": "REG-004", "title": "California Wildfire Risk Guidance", "jurisdiction": "state-CA", "effective_date": "2024-04-01", "category": "wildfire"}
        },
        {
            "id": "REG-005",
            "doc": "NAIC Third-Party AI Oversight Framework - Anticipated 2026 Requirements: Based on NAIC Innovation, Cybersecurity, and Technology Committee discussions through December 2025. Expected adoption mid-2026. Key Anticipated Requirements: (1) Insurers must maintain an AI governance framework that includes board-level oversight, designated AI risk officer, and annual AI risk assessment. (2) Third-party AI vendors must provide model cards documenting training data, known limitations, bias testing results, and performance metrics. (3) Insurers must conduct independent validation of third-party AI models before deployment and at least annually thereafter. (4) AI model drift monitoring: Insurers must track model performance over time and re-validate when performance degrades beyond defined thresholds. (5) Consumer appeal rights: Policyholders must have the right to request human review of any AI-influenced decision within 30 days. (6) Annual AI usage report: Insurers must file annual reports detailing AI use cases, data sources, consumer complaints related to AI decisions, and corrective actions taken. (7) Algorithmic impact assessments required before deploying AI in new use cases affecting consumers. RiskMind readiness: The Glass Box architecture provides the transparency framework required. Data sources registry documents all third-party inputs. Human-in-the-loop workflow ensures oversight. Confidence scoring enables automated escalation. Reference: NAIC Innovation Committee Exposure Draft 2025, expected final adoption Q2 2026.",
            "meta": {"type": "regulatory", "reg_id": "REG-005", "title": "NAIC Third-Party AI Oversight 2026", "jurisdiction": "federal", "effective_date": "2026-06-01", "category": "ai_governance"}
        },
    ]

    for r in regs:
        reg_ids.append(r["id"])
        reg_docs.append(r["doc"])
        reg_metas.append(r["meta"])

    knowledge_col.upsert(ids=reg_ids, documents=reg_docs, metadatas=reg_metas)
    print(f"[OK] Upserted {len(reg_ids)} regulatory documents")

    # ========================================================================
    # SECTION 4: 3 cat model / risk commentary documents
    # ========================================================================
    cat_ids = []
    cat_docs = []
    cat_metas = []

    cats = [
        {
            "id": "CAT-001",
            "doc": "2026 Hurricane Season Outlook - Impact on Gulf Coast Portfolio. Source: RMS/Moody's Analytics, January 2026 update. The 2026 Atlantic hurricane season (June-November) is projected to be above average for the third consecutive year. NOAA forecasts 14-21 named storms, 6-10 hurricanes, and 3-5 major hurricanes (Category 3+). Key factors: Persistently warm sea surface temperatures in the Gulf of Mexico and Caribbean. La Nina conditions expected to continue through summer 2026, historically correlated with increased Gulf landfall probability. The RiskMind portfolio has significant Gulf exposure: CRESTA zone US-FL-001 contains 2 policies with combined wind PML of $1.87M, and US-TX-003 contains 2 policies with combined wind/hail PML of $1.1M. Recommended actions: (1) Review all coastal FL and TX policies for adequate hurricane deductibles per Section 8.2.1, (2) Verify zone accumulation does not breach PML limits per Section 8.3.2, (3) Consider temporary moratorium on new coastal business from May through November, (4) Confirm reinsurance treaty coverage for the projected loss levels, (5) Pre-position claims response for rapid deployment. Current portfolio wind AAL: $42K (FL) + $18K (TX) = $60K annual expected hurricane loss.",
            "meta": {"type": "cat_commentary", "cat_id": "CAT-001", "title": "2026 Hurricane Season Outlook", "region": "Gulf-South", "date": "2026-01-10"}
        },
        {
            "id": "CAT-002",
            "doc": "FEMA Flood Map Revision Analysis - Zone Upgrades Affecting TX/FL Portfolio Policies. Source: FEMA NFHL update December 2025, First Street Foundation verification. Three RiskMind portfolio policies have been affected by recent FEMA flood zone remapping: (1) COMM-2024-005 (FastTrack Logistics, Dallas TX) - remapped from Zone X to Zone X with notation of increased residual risk. Flood risk score increased from 15 to 28 based on First Street Foundation 2026 model incorporating climate projections. (2) COMM-2024-014 (OceanView Hotels, Orlando FL) - upgraded from Zone X to Zone AE. This is significant: Zone AE designation means the property is now in the 1% annual chance floodplain. Per Section 8.2.2, AE zone requires flood sublimit endorsement, current elevation certificate, and minimum $100K flood deductible. Premium adjustment of 15-25% recommended. (3) COMM-2024-017 (BlueSky Development, Austin TX) - upgraded from Zone X to Zone AE. Same requirements as COMM-2024-014. Austin has experienced 3 significant flooding events since 2018 due to rapid development and impervious surface increase. All three policies are flagged with flood_zone_change_flag = 'UPGRADED' in the database. Recommended actions: (1) Issue mid-term endorsements adding flood sublimits for AE-designated policies, (2) Request elevation certificates within 30 days, (3) Notify policyholders of zone change and coverage implications, (4) Review pricing adequacy given increased flood exposure. Estimated additional flood AAL for upgraded properties: +$12K combined.",
            "meta": {"type": "cat_commentary", "cat_id": "CAT-002", "title": "FEMA Flood Map Revision Analysis", "region": "Gulf-South", "date": "2026-01-15"}
        },
        {
            "id": "CAT-003",
            "doc": "Regional Risk Trends Q4 2025 - Hail, Wildfire, and Earthquake Exposure Update. Source: RMS v23 quarterly monitor, NOAA SPC storm reports, Cal Fire statistics. (1) HAIL - Central Texas/Colorado: Severe convective storm (SCS) activity increased 22% in 2025 versus 5-year average. Dallas-Fort Worth metroplex experienced 18 significant hail events in the past 5 years, with 6 exceeding 2-inch diameter. Portfolio impact: COMM-2024-005 (Dallas) and COMM-2024-017 (Austin) in CRESTA US-TX-003 have combined hail PML of $1.1M. Denver area (COMM-2024-003) had 12 hail events. Roofing material is critical: metal and tile roofs show 60% lower hail damage rates than shingle roofs. Recommend: verify roof type for TX/CO policies, consider hail-specific deductible endorsement. (2) WILDFIRE - California: 2025 wildfire season was the second-worst on record with 890,000 acres burned. RiskMind portfolio has 3 CA policies with varying wildfire exposure: US-CA-001 (Los Angeles, score 62), US-CA-002 (San Francisco, score 22), US-CA-003 (Bakersfield, score 55). COMM-2024-011 in LA has the highest exposure at 62 - approaching but not breaching Section 8.2.3 threshold of 70. Recommend: proactive loss control inspection for policies with score above 50. (3) EARTHQUAKE - Pacific Northwest: The Cascadia Subduction Zone remains a significant long-tail risk for Seattle (COMM-2024-012) and Portland (COMM-2024-018) policies. Combined earthquake PML: $570K. No change in seismicity trends but academic research suggests elevated probabilities for M7+ event within next 50 years. Recommend: verify earthquake sublimits are adequate and review deductible levels.",
            "meta": {"type": "cat_commentary", "cat_id": "CAT-003", "title": "Regional Risk Trends Q4 2025", "region": "National", "date": "2026-01-20"}
        },
    ]

    for c in cats:
        cat_ids.append(c["id"])
        cat_docs.append(c["doc"])
        cat_metas.append(c["meta"])

    knowledge_col.upsert(ids=cat_ids, documents=cat_docs, metadatas=cat_metas)
    print(f"[OK] Upserted {len(cat_ids)} cat commentary documents")

    # ========================================================================
    # SECTION 5: 2023 claims (matching SQLite enrichment)
    # ========================================================================
    claim_ids = []
    claim_docs = []
    claim_metas = []

    claims_2023 = [
        {"id": "claim_CLM-2023-001", "cn": "CLM-2023-001", "pn": "COMM-2024-003", "name": "SafeBuild Construction", "ind": "Construction", "type": "workers_compensation", "amt": 45000, "status": "closed", "date": "2023-02-15", "desc": "Scaffolding collapse during exterior work, two workers injured"},
        {"id": "claim_CLM-2023-002", "cn": "CLM-2023-002", "pn": "COMM-2024-003", "name": "SafeBuild Construction", "ind": "Construction", "type": "property_damage", "amt": 28000, "status": "closed", "date": "2023-05-20", "desc": "Excavator damaged underground utility line during site prep"},
        {"id": "claim_CLM-2023-003", "cn": "CLM-2023-003", "pn": "COMM-2024-003", "name": "SafeBuild Construction", "ind": "Construction", "type": "workers_compensation", "amt": 65000, "status": "closed", "date": "2023-08-10", "desc": "Heavy equipment rollover, operator hospitalized"},
        {"id": "claim_CLM-2023-004", "cn": "CLM-2023-004", "pn": "COMM-2024-003", "name": "SafeBuild Construction", "ind": "Construction", "type": "property_damage", "amt": 15000, "status": "closed", "date": "2023-11-05", "desc": "Weather damage to materials stored on-site"},
        {"id": "claim_CLM-2023-005", "cn": "CLM-2023-005", "pn": "COMM-2024-011", "name": "BuildRight Contractors", "ind": "Construction", "type": "workers_compensation", "amt": 120000, "status": "closed", "date": "2023-03-22", "desc": "Trench collapse at residential development site"},
        {"id": "claim_CLM-2023-006", "cn": "CLM-2023-006", "pn": "COMM-2024-011", "name": "BuildRight Contractors", "ind": "Construction", "type": "property_damage", "amt": 38000, "status": "closed", "date": "2023-07-14", "desc": "Crane boom struck adjacent structure during lift"},
        {"id": "claim_CLM-2023-007", "cn": "CLM-2023-007", "pn": "COMM-2024-011", "name": "BuildRight Contractors", "ind": "Construction", "type": "environmental", "amt": 22000, "status": "closed", "date": "2023-10-30", "desc": "Diesel fuel spill from generator at construction site"},
        {"id": "claim_CLM-2023-008", "cn": "CLM-2023-008", "pn": "COMM-2024-016", "name": "Eagle Transport Co", "ind": "Transportation", "type": "auto_accident", "amt": 8500, "status": "closed", "date": "2023-04-18", "desc": "Minor fender bender during delivery route"},
        {"id": "claim_CLM-2023-009", "cn": "CLM-2023-009", "pn": "COMM-2024-016", "name": "Eagle Transport Co", "ind": "Transportation", "type": "property_damage", "amt": 6000, "status": "closed", "date": "2023-09-25", "desc": "Cargo strap failure, minor product damage"},
        {"id": "claim_CLM-2023-010", "cn": "CLM-2023-010", "pn": "COMM-2024-005", "name": "FastTrack Logistics", "ind": "Transportation", "type": "auto_accident", "amt": 11000, "status": "closed", "date": "2023-06-12", "desc": "Backing accident at loading dock"},
        {"id": "claim_CLM-2023-011", "cn": "CLM-2023-011", "pn": "P-1023", "name": "Northwind Logistics", "ind": "Transportation", "type": "auto_accident", "amt": 9500, "status": "closed", "date": "2023-03-08", "desc": "Side-mirror collision with parked vehicle"},
        {"id": "claim_CLM-2023-012", "cn": "CLM-2023-012", "pn": "P-1023", "name": "Northwind Logistics", "ind": "Transportation", "type": "property_damage", "amt": 7000, "status": "closed", "date": "2023-10-15", "desc": "Pallet jack damaged warehouse floor"},
        {"id": "claim_CLM-2023-013", "cn": "CLM-2023-013", "pn": "COMM-2024-004", "name": "MedCare Health Services", "ind": "Healthcare", "type": "professional_liability", "amt": 35000, "status": "closed", "date": "2023-05-10", "desc": "Patient alleged delayed diagnosis of condition"},
        {"id": "claim_CLM-2023-014", "cn": "CLM-2023-014", "pn": "COMM-2024-004", "name": "MedCare Health Services", "ind": "Healthcare", "type": "general_liability", "amt": 8000, "status": "closed", "date": "2023-09-22", "desc": "Visitor tripped on uneven parking lot surface"},
        {"id": "claim_CLM-2023-015", "cn": "CLM-2023-015", "pn": "COMM-2024-015", "name": "PrimeCare Dental", "ind": "Healthcare", "type": "professional_liability", "amt": 12000, "status": "closed", "date": "2023-07-18", "desc": "Patient alleged nerve damage during dental procedure"},
        {"id": "claim_CLM-2023-016", "cn": "CLM-2023-016", "pn": "COMM-2024-020", "name": "PetCare Animal Hospital", "ind": "Healthcare", "type": "professional_liability", "amt": 9500, "status": "closed", "date": "2023-11-05", "desc": "Pet owner claimed misdiagnosis led to extended treatment"},
        {"id": "claim_CLM-2023-017", "cn": "CLM-2023-017", "pn": "COMM-2024-001", "name": "ABC Manufacturing Inc", "ind": "Manufacturing", "type": "product_liability", "amt": 42000, "status": "closed", "date": "2023-04-22", "desc": "Defective manufactured component caused client equipment failure"},
        {"id": "claim_CLM-2023-018", "cn": "CLM-2023-018", "pn": "COMM-2024-009", "name": "IronWorks Fabrication", "ind": "Manufacturing", "type": "product_liability", "amt": 18000, "status": "closed", "date": "2023-08-15", "desc": "Custom fabricated part failed under load at customer site"},
        {"id": "claim_CLM-2023-019", "cn": "CLM-2023-019", "pn": "COMM-2024-002", "name": "XYZ Restaurant Group", "ind": "Restaurant", "type": "business_interruption", "amt": 55000, "status": "closed", "date": "2023-06-30", "desc": "Health department closure after kitchen fire, 3 weeks lost revenue"},
        {"id": "claim_CLM-2023-020", "cn": "CLM-2023-020", "pn": "COMM-2024-014", "name": "OceanView Hotels", "ind": "Hospitality", "type": "business_interruption", "amt": 85000, "status": "closed", "date": "2023-09-01", "desc": "Hurricane forced 2-week closure during peak season"},
        {"id": "claim_CLM-2023-021", "cn": "CLM-2023-021", "pn": "COMM-2024-019", "name": "SteelEdge Manufacturing", "ind": "Manufacturing", "type": "environmental", "amt": 32000, "status": "closed", "date": "2023-03-18", "desc": "Chemical storage leak required EPA-supervised cleanup"},
        {"id": "claim_CLM-2023-022", "cn": "CLM-2023-022", "pn": "COMM-2024-013", "name": "SunValley Farms", "ind": "Agriculture", "type": "property_damage", "amt": 28000, "status": "closed", "date": "2023-07-28", "desc": "Irrigation system failure flooded storage building"},
        {"id": "claim_CLM-2023-023", "cn": "CLM-2023-023", "pn": "COMM-2024-012", "name": "DataShield Cybersec", "ind": "Technology", "type": "cyber_breach", "amt": 45000, "status": "closed", "date": "2023-05-14", "desc": "Client suffered data exfiltration via phishing attack on managed endpoint"},
        {"id": "claim_CLM-2023-024", "cn": "CLM-2023-024", "pn": "COMM-2024-006", "name": "TechNova Solutions", "ind": "Technology", "type": "cyber_breach", "amt": 12000, "status": "closed", "date": "2023-11-20", "desc": "Internal code repository exposed to unauthorized access for 48 hours"},
    ]

    for cl in claims_2023:
        claim_ids.append(cl["id"])
        doc = (
            f"{cl['type']} claim on policy {cl['pn']} ({cl['name']}, {cl['ind']}). "
            f"Date: {cl['date']}. Amount: ${cl['amt']:,.2f}. Status: {cl['status']}. "
            f"Details: {cl['desc']}"
        )
        claim_docs.append(doc)
        claim_metas.append({
            "type": "claim",
            "claim_number": cl["cn"],
            "claim_type": cl["type"],
            "policy_number": cl["pn"],
            "policyholder": cl["name"],
            "industry": cl["ind"],
            "amount": float(cl["amt"]),
            "status": cl["status"],
        })

    knowledge_col.upsert(ids=claim_ids, documents=claim_docs, metadatas=claim_metas)
    print(f"[OK] Upserted {len(claim_ids)} claim documents from 2023")

    # ========================================================================
    # SUMMARY
    # ========================================================================
    print(f"\n=== CHROMADB ENRICHMENT SUMMARY ===")
    print(f"  Guidelines collection: {guidelines_col.count()} documents")
    print(f"  Knowledge collection:  {knowledge_col.count()} documents")
    print(f"    - Claims (original + 2023): ~79")
    print(f"    - Decisions: 15")
    print(f"    - Regulatory: 5")
    print(f"    - Cat commentary: 3")
    print(f"\n[DONE] ChromaDB enrichment complete.")


if __name__ == "__main__":
    run()
